<?php

// Message Pack for Discuz! Plus Version 1.0.0
// Created by HKLCF

$language = array
(

	'credit_title' => '積分',
	'credit_unit' => '點',

	'title' => '標題',
	'never' => '從未',
	'online' => '在線',
	'onlines' => '人在線',
	'on' => '於',
	'total' => '共',
	'admin' => '管理員',
	'supermod' => '超級版主',
	'moderator' => '版主',
	'vip' => 'VIP',
	'member' => '會員',
	'invisible'=> '隱身會員',
	'guest' => '訪客',
	'forum' => '論壇',
	'refresh' => '重 新 整 理',
	'show' => '查看',
	'submit' => '提 &nbsp; 交',
	'disable' => '禁用',
	'enable' => '啟用',
	'select' => '選擇',
	'reply' => '回覆',
	'download' => '下載',
	'forward' => '轉發',
	'delete' => '刪除',
	'content' => '內容',
	'time' => '時間',

	'online' => '在線',
	'offline' => '離線',
	'show' => '現身',
	'hide' => '隱身',
	'action' => '動作',
	'options' => '選項',
	'username' => '用戶名',
	'email' => 'E-mail',
	'tuijianren' => '推薦人',
	'tuijianren2' => '你填寫後，這個推薦人會加 $credit_tuijianren 分',
	'old_password' => '原密碼',
	'password' => '密碼',
	'password_confirm' => '確認密碼',
	'new_password' => '新密碼',
	'new_password_confirm' => '確認新密碼',
	'gender' => '性別',
	'homepage' => '主頁',
	'location' => '來自',
	'regip' => '註冊 IP',
	'regdate' => '註冊日期',
	'lastvisit' => '上次訪問',
	'postnum' => '發貼',
	'avatar' => '頭像',
	'avatars' => '張頭像',
	'male' => '男',
	'female' => '女',
	'secret' => '保密',
	'birthday' => '生日',
	'status' => '頭銜',
	'usergroup' => '用戶組',
	'rank' => '發表量級別',
	'pm' => '短訊息',
	'register' => '註冊',
	'register_now' => '立即註冊',
	'memberlist' => '會員',
	'login' => '登錄',
	'logout' => '退出',
	'search' => '搜尋',
	'statistics' => '統計',
	'memo' => '備忘錄',
	'memcp' => '控制面板',
	'admincp' => '系統設置',
	'faq' => '幫助',
	'style' => '界面風格',
	'tpp' => '每頁主題數',
	'ppp' => '每頁文章數',
	'timeformat' => '時間格式',
	'dateformat' => '日期格式',
	'timeoffset' => '時間校正 (香港時間 +8)，目前GMT標準時間 $currtime',
	'custom_status' => '自定義頭銜',
	'bio' => '自我介紹',
	'signature' => '個人簽名',
	'bytes_limited' => '字節以內',
	'lower_than' => '小於',
	'is_unlimited' => '為不限制',
	'etc' => '等',
	'is' => '狀態',
	'return' => '返回',
	'goback_home' => '返回',
	'timenow' => '現在時間是',
	'welcometo' => '歡迎光臨',
	'your_lastvisit' => '您上次訪問是在',
	'use_default' => '- 使用默認 -',
	'default' => '默認',
	'or' => '或',
	'to' => '到',
	'from' => '來自',
	'year' => '年',
	'month' => '月',
	'day' => '日',
	'hour' => '小時',
	'level' => '級別',

	'icon' => '圖標',
	'author' => '作者',
	'subject' => '標題',
	'replies' => '回覆',
	'views' => '查看',
	'posts' => '篇',
	'downloads' => '下載次數',
	'lastpost' => '最後發表',
	'message' => '內容',
	'poston' => '發表於',
	'attachment' => '附件',
	'curr_attachment' => '當前附件',
	'attachment_preserve' => '保留附件',
	'attachment_delete' => '刪除附件',
	'attachment_upload' => '上傳新附件',
	'attachment_allow_exts' => '可用擴展名',
	'delete_check' => '刪',

	'send' => '發送',
	'bytes' => '字節',
	'optional' => '可選',
	'contactus' => '聯繫我們',
	'board_allowed' => '系統限制',
	'board_message' => '提示訊息',
	'agree' => '同 意',
	'disagree' => '不同意',
	'go_back' => '返回上一頁',

	'required_info' => '必填內容',
	'optional_info' => '選填內容',
	'optional' => '可選',
	'board_options' => '論壇個性化設置',
	'other_options' => '其他選項',
	'show_email_addr' => 'E-mail 地址可見',
	'allow_newsletter' => '同意接收論壇通知 (E-mail 或短訊息)',
	'image_comment' => '如使用 Flash 動畫，請用逗號隔開 URL，寬度和高度，如「http://your.com/avatar.swf,80,40」',

	'announcements' => '論壇公告',
	'starttime' => '起始時間',
	'endtime' => '結束時間',
	'unlimited' => '不限',

	'emailfriend' => '推薦給朋友',
	'your_name' => '您的名字',
	'your_email' => '您的 E-mail',
	'receiver_name' => '接收者名字',
	'receiver_email' => '接收者 E-mail',
	'recommend_toyou' => '向您推薦',
	'recommend_message' => '您好！我在 $bbname ($boardurl){LF}看到了這篇文章，認為很有價值，特推薦給您。{LF}{LF}$thread[subject]{LF}地址 $threadurl{LF}{LF}希望你能喜歡。',

	'forum_important_threads' => '重要主題',
	'forum_normal_threads' => '普通主題',
	'forum_modedby' => '版主',
	'forum_opening' => '空缺中',
	'forum_viewall' => '查看全部主題',
	'forum_viewdigest' => '查看本版精華',
	'forum_delthreads' => '刪除選定主題',
	'forum_activemember' => '正在瀏覽此論壇的會員',
	'forum_thread_delete' => '刪',
	'forum_thread_close' => '關',
	'forum_thread_move' => '移',
	'forum_thread_top' => '頂',
	'forum_thread_bump' => '提',
	'forum_thread_digest' => '精',
	'forum_thread_highlight' => '亮',
	'forum_nothreads' => '本論壇或指定的範圍內尚無主題。',
	'forum_jump' => '論壇跳轉',
	'forum_password_require' => '本論壇需要密碼，您必須在下面輸入正確的密碼才能瀏覽這個論壇。',

	'digest' => '精華區',
	'digest_forum' => '以下論壇精華區',

	'threads_all' => '全部主題',
	'threads_digest' => '精華主題',
	'last_1_days' => '1 天以來',
	'last_2_days' => '2 天以來',
	'last_7_days' => '1 周以來',
	'last_30_days' => '1 個月以來',
	'last_90_days' => '3 個月以來',
	'last_180_days' => '6 個月以來',
	'last_356_days' => '1 年以來',
	'order_desc' => '按降序排列',
	'order_asc' => '按升序排列',

	'thread_moved' => '移動',
	'thread_digest' => '精華',
	'thread_sticky' => '置頂',
	'thread_poll' => '投票',

	'thread_newposts' => '有新回覆',
	'thread_nonewpost' => '無新回覆',
	'thread_more_replies' => '多於 $hottopic 篇回覆',
	'thread_closed' => '關閉的主題',

	'creditsrequire_view' => '瀏覽所需',
	'creditsrequire_attach' => '下載附件所需',
	'require' => '所需',

	'post_subject_and_message_isnull' => '請完成標題或內容欄。',
	'post_subject_or_message_isnull' => '請完成標題和內容欄。',
	'post_message_toolong' => '您的文章長度不符合要求',
	'post_currlength' => '當前長度',
	'post_fastpost' => '快速發新話題',
	'post_fastreply' => '快速回覆主題',
	'post_parseurl' => 'URL 識別',
	'post_smilies' => 'Smilies',
	'post_discuzcode' => 'Discuz! 代碼',
	'post_discuzcode_normal_mode' => '提示插入',
	'post_discuzcode_normal_mode_comment' => '點擊代碼按鈕後出現嚮導窗口幫助您完成代碼插入',
	'post_discuzcode_help_mode' => '幫助訊息',
	'post_discuzcode_help_mode_comment' => '點擊相應的代碼按鈕即可獲得相應的說明和提示',
	'post_discuzcode_adv_mode' => '直接插入',
	'post_discuzcode_adv_mode_comment' => '點擊代碼按鈕後不出現提示即直接插入相應代碼',
	'post_discuzcode_extra_font' => '<option value="細明體">細明體</option><option value="標楷體">標楷體</option>',
	'post_discuzcode_fontsize' => '設置字號',
	'post_discuzcode_fontsize_comment' => '將標籤所包圍的文字設置成指定字號。\n例如：[size=3]文字大小為 3[/size]',
	'post_discuzcode_fontsize_normal' => '請輸入要設置為指定字號的文字。',
	'post_discuzcode_font' => '設定字體',
	'post_discuzcode_font_comment' => '將標籤所包圍的文字設置成指定字體。\n例如：[font=新細明體]字體為新細明體[/font]',
	'post_discuzcode_font_normal' => '請輸入要設置成指定字體的文字。',
	'post_discuzcode_color' => '定義文本顏色',
	'post_discuzcode_color_comment' => '將標籤所包圍的文本變為制定顏色。\n例如：[color=red]紅顏色[/color]',
	'post_discuzcode_color_normal' => '請輸入要設置成指定顏色的文字。',
	'post_discuzcode_bold' => '插入粗體文本',
	'post_discuzcode_bold_comment' => '將標籤所包圍的文本變成粗體。\n例如：[b]Crossday 工作室[/b]',
	'post_discuzcode_bold_normal' => '請輸入要設置成粗體的文字。',
	'post_discuzcode_italicize' => '插入斜體文本',
	'post_discuzcode_italicize_comment' => '將標籤所包圍的文本變成斜體。\n例如：[i]Crossday 工作室[/i]',
	'post_discuzcode_italicize_normal' => '請輸入要設置成斜體的文字。',
	'post_discuzcode_underline' => '插入字下線',
	'post_discuzcode_underline_comment' => '給標籤所包圍的文本加上字下線。\n例如：[u]網路觀點工作室[/u]',
	'post_discuzcode_underline_normal' => '請輸入要加字下線的文字。',
	'post_discuzcode_center' => '居中對齊',
	'post_discuzcode_center_comment' => '將標籤所包圍的文本居中對齊顯示。\n例如：[align=center]內容居中[/align]',
	'post_discuzcode_center_normal' => '請輸入要居中對齊的文字。',
	'post_discuzcode_hyperlink' => '插入超連結',
	'post_discuzcode_hyperlink_comment' => '插入一個超連結。\n例如：\n[url]http://www.crossday.com[/url]\n[url=http://www.crossday.com]Crossday 工作室[/url]',
	'post_discuzcode_hyperlink_normal' => '請輸入連結顯示的文字，如果留空則直接顯示連結。',
	'post_discuzcode_hyperlink_normal_input' => '請輸入 URL。',
	'post_discuzcode_email' => '插入郵件地址',
	'post_discuzcode_email_comment' => '插入郵件地址連結。\n例如：\n[email]support@crossday.com[/email]\n[email=support@crossday.com]Dai Zhikang[/email]',
	'post_discuzcode_email_normal' => '請輸入連結顯示的文字，如果留空則直接顯示郵件地址。',
	'post_discuzcode_email_normal_input' => '請輸入郵件地址。',
	'post_discuzcode_image' => '插入圖像',
	'post_discuzcode_image_comment' => '在文本中插入一幅圖像。\n例如：[img]http://www.crossday.com/cdb/images/logo.gif[/img]',
	'post_discuzcode_image_normal' => '請輸入圖像的 URL。',
	'post_discuzcode_flash' => '插入 flash',
	'post_discuzcode_flash_comment' => '在文本中插入 flash 動畫。\n例如：[swf]http://www.crossday.com/cdb/images/banner.swf[/swf]',
	'post_discuzcode_flash_normal' => '請輸入 flash 動畫的 URL。',
	'post_discuzcode_code' => '插入代碼',
	'post_discuzcode_code_comment' => '插入程式或腳本原始代碼。\n例如：[code]echo\"這裡是我們的論壇\";[/code]',
	'post_discuzcode_code_normal' => '請輸入要插入的代碼。',
	'post_discuzcode_quote' => '插入引用',
	'post_discuzcode_quote_comment' => '將標籤所包圍的文本作為引用特殊顯示。\n例如：[quote]Discuz! 著作權所有 - Crossday Studio[/quote]',
	'post_discuzcode_quote_normal' => '請輸入要作為引用顯示的文字。',
	'post_discuzcode_hide' => '插入隱藏',
	'post_discuzcode_hide_comment' => '將標籤所包圍的文本作為隱藏範圍。\n例如：[hide]這是秘密[/hide]',
	'post_discuzcode_hide_normal' => '請輸入要隱藏的文字。',
	'post_discuzcode_list' => '插入列表',
	'post_discuzcode_list_comment' => '插入可由瀏覽器顯示來的規則列表項。\n例如：\n[list]\n[*]；列表項 #1\n[*]；列表項 #2\n[*]；列表項 #3\n[/list]',
	'post_discuzcode_list_normal' => '請選擇列表格式：字母式列表輸入 \"A\"；數字式列表輸入 \"1\"。此處也可留空。',
	'post_discuzcode_list_normal_error' => '錯誤：列表格式只能選擇輸入 \\"A\\" 或 \\"1\\"。',
	'post_discuzcode_list_normal_input' => '請輸入列表項目內容，如果留空表示項目結束。',
	'post_imgcode' => '[img] 代碼',
	'post_show_sig' => '使用個人簽名',
	'post_email_notify' => '接收新回覆郵件通知',
	'post_topicsubmit' => '發表文章',
	'post_previewpost' => '預覽文章',
	'post_topicreset' => '清空內容',
	'post_thread_review' => '主題回顧',
	'post_replies_toolong' => '本主題回覆較多，請 <a href="viewthread.php?fid=$fid&tid=$tid">點擊這裡</a> 查看。',
	'post_submit_hotkey' => '[完成後可按 Ctrl+Enter 發布]',
	'post_newthread' => '發新話題',
	'post_newreply' => '發表回覆',
	'post_editpost' => '編輯文章',
	'post_poll_options' => '投票選項',
	'post_poll_comment' => '每個選項一行，最多十行',
	'post_poll_allowmultiple' => '多選投票',
	'post_check_length' => '字數檢查',
	'post_delpost' => '刪除本篇文章',
	'post_top_thread' => '主題置頂',
	'post_digest_thread' => '精華文章',

	'getpassword' => '取回密碼',

	'index_your' => '您的',
	'index_status' => '頭銜',
	'index_threads' => '篇主題',
	'index_posts' => '篇文章',
	'index_activemembers' => '在線用戶',
	'index_members' => '位會員',
	'index_invisibles' => '隱身',
	'index_guests' => '位訪客',
	'index_mostonlines' => '最高紀錄是',
	'index_users' => '人',
	'show_newthreads' => '查看新文章',
	'show_mytopics' => '我的話題',
	'mark_read' => '標記已讀',
	'welcome_newmember' => '歡迎新會員',
	'index_announcements' => '公告',
	'index_noannouncement' => '到目前為止沒有論壇公告。',
	'forum_name' => '論壇',
	'forum_threads' => '主題',
	'forum_posts' => '文章數',
	'forum_lastpost' => '最後發表',
	'subforum_show' => '子 版 列 表',
	'forum_moderators' => '版主',
	'forum_newposts' => '有新文章的論壇',
	'forum_nonewpost' => '無新文章的論壇',
	'board_links' => '聯盟論壇',
	'index_showonlinedetails' => '打開在線列表',
	'index_hideonlinedetails' => '關閉在線列表',
	'private_forum' => '私密論壇',
	'private_forums' => '-',

	'thread_rate' => '參與評分',
	'thread_rating' => '評分',

	'member_login' => '會員登錄',
	'member_logout' => '退出登錄',
	'cookie_time' => 'Cookie 有效期',
	'one_year' => '一年',
	'one_month' => '一個月',
	'one_day' => '一天',
	'one_hour' => '一小時',
	'this_task' => '瀏覽器進程',
	'related_faq' => '相關幫助',

	'login_invisible' => '隱身登錄',
	'login_normal_mode' => '正常模式',
	'login_invisible_mode' => '隱身模式',

	'security_question' => '安全提問',
	'security_answer' => '回答',
	'security_question_0' => '不使用安全提問',
	'security_question_1' => '母親的名字',
	'security_question_2' => '爺爺的名字',
	'security_question_3' => '父親出生的城市',
	'security_question_4' => '您其中一位老師的名字',
	'security_question_5' => '您個人計算机的型號',
	'security_question_6' => '您最喜歡的餐館名稱',
	'security_question_7' => '駕駛執照的最后四位數字',

	'member_list' => '會員列表',
	'member_search' => '搜尋用戶',
	'member_orderby' => '用戶訊息以...排序',

	'memcp_welcome' => '您好 $discuz_userss ，歡迎進入控制面板，這裡提供相關的資料設定與論壇快捷功能等。',
	'memcp_home' => '控制面板首頁',
	'memcp_info' => '帳號訊息',
	'memcp_buddylist' => '好友列表',
	'memcp_buddylist_add' => '添加',
	'memcp_buddylist_remove' => '刪除該好友',
	'memcp_last_5_pm' => '最近的五條短訊息',
	'memcp_nopm' => '目前收件箱中沒有短訊息。',
	'memcp_last_5_subs' => '最近被回覆的五個訂閱主題',
	'memcp_nosubs' => '目前沒有被訂閱的主題。',
	'memcp_nofavs' => '目前沒有被收藏的主題。',
	'memcp_avatar_list' => '論壇頭像列表',
	'memcp_profile' => '編輯個人資料',
	'memcp_profile_passwd_comment' => '如不需要更改密碼，此處請留空',
	'memcp_profile_email_comment' => '如更改地址，系統將修改您的密碼並重新驗證其有效性，請慎用。',
	'memcp_profile_security_keep' => '保持原有的安全提問和答案',
	'memcp_profile_security_comment' => '如您設置新的安全提問，請在此輸入答案',
	'memcp_subscriptions' => '訂閱列表',
	'memcp_favorites' => '收藏夾',
	'memcp_avatar_upload' =>'頭像上傳',
	'memcp_avatar_upload_note'=>'I. 注意事項',
	'memcp_avatar_upload_location'=>'II. 上傳位置',
	'memcp_avatar_upload_tips'=>'1. 上傳的頭像格式只限 <strong>.JPG</strong> 和 <strong>.GIF</strong>。<br>2. 上傳的檔大小不得超過 1024KB。<br>3. 上傳的頭像寬和高均不得超過 $maxavatarsize 位元。',

	'reportpost' => '報告文章',
	'reportpost_suggestion' => '我的意見',
	'reportpost_reason' => '我對這個文章有異議，特向您報告',

	'search_keywords' => '關鍵字',
	'search_keywords_comment' => '關鍵字中可使用萬用字元 "*"<br><br>匹配多個關鍵字全部，可用空格或 "AND" 連結。如 win32 AND unix<br>匹配多個關鍵字其中部分，可用 "|" 或 "OR" 連結。如 win32 OR unix',
	'search_username_comment' => '用戶名中可使用萬用字元 "*"，如 *user*',
	'search_range' => '搜尋範圍',
	'search_orderby' => '排序類型',
	'search_all_forums' => '搜尋所有開放的論壇',
	'search_titleonly' => '只搜尋標題',
	'search_fulltext' => '搜尋文章內容',
	'search_any_date' => '全部時間',
	'1_days_ago' => '1 天前',
	'2_days_ago' => '2 天前',
	'7_days_ago' => '1 周前',
	'30_days_ago' => '1 個月前',
	'90_days_ago' => '3 個月前',
	'180_days_ago' => '6 個月前',
	'356_days_ago' => '1 年前',
	'search_newer' => '之後',
	'search_older' => '之前',
	'search_lastpost' => '最後回覆時間',
	'search_views' => '被瀏覽次數',
	'search_replies' => '被回覆次數',
	'search_navigation' => '頁碼導航',
	'search_gradual' => '漸進連結',
	'search_next_page' => '下 $tpp 條匹配結果',
	'search_total_results' => '共 $total 個結果',
	'search_nomatch' => '對不起，沒有找到匹配結果。',

	'message_forward' => '如果您的瀏覽器沒有自動跳轉，請點擊這裡。',
	'message_go_back' => '[ 點擊這裡返回上一頁 ]',
	
	'stats' => '論壇統計',
	'stats_rank' => '排行榜',
	'stats_main' => '基本概況',
	'stats_week' => '星期流量',
	'stats_hour' => '時段流量',
	'stats_agent' => '客戶軟體',
	'stats_threads' => '主題排行',
	'stats_members' => '會員排行',
	'stats_main_member' => '會員統計',
	'stats_main_board' => '論壇統計',
	'stats_main_members' => '註冊會員',
	'stats_main_admins' => '管理成員',
	'stats_main_new' => '新會員',
	'stats_main_topposter' => '今日論壇之星',
	'stats_main_total_posted' => '發表文章數',
	'stats_main_posters' => '發表文章會員',
	'stats_main_nonposters' => '未發表文章會員',
	'stats_main_posters_percent' => '發表文章會員占總數',
	'stats_main_posts_avg' => '平均每人發表文章數',
	'stats_main_members_count' => '會員數',
	'stats_main_forums_count' => '論壇數',
	'stats_main_threads_count' => '主題數',
	'stats_main_posts_count' => '文章數',
	'stats_main_rpt' => '平均每個主題被回覆次數',
	'stats_main_nppd' => '平均每日新增文章數',
	'stats_main_todays_newposts' => '最近 24 小時新增文章數',
	'stats_main_hot_forum' => '最熱門的論壇',
	'stats_main_board_activity' => '論壇活躍指數',
	'stats_main_pageview' => '流量概況',
	'stats_main_total_pageview' => '總頁面流量',
	'stats_main_person_time' => '人次',
	'stats_main_total_visitors' => '共計來訪',
	'stats_main_pv_avg' => '平均每人瀏覽',
	'stats_main_maxpv_month' => '被訪問最多的月份： <span class="bold">$maxmonth_year</span> 年 <span class="bold">$maxmonth_month</span> 月',
	'stats_main_period_of_time' => '時段',
	'stats_main_month' => '月份流量',
	'stats_posts' => '發表文章',
	'stats_posts_thismonth' => '本月發表文章',
	'stats_posts_today' => '今日發表文章',
	'stats_os' => '操作系統',
	'stats_browser' => '瀏覽器',
	'stats_threads_most_views' => '被瀏覽最多的主題',
	'stats_threads_most_replies' => '被回覆最多的主題',

	'admin_modoptions' => '管理選項',
	'admin_bump' => '提升主題',
	'admin_stick' => '主題置頂',
	'admin_unstick' => '解除置頂',
	'admin_stick_global' => '全論壇置頂',
	'admin_stick_unstick' => '置頂/解除置頂',
	'admin_split' => '分割主題',
	'admin_split_newsubject' => '新主題的標題',
	'admin_open' => '打開主題',
	'admin_close' => '關閉主題',
	'admin_openclose' => '關閉/打開主題',
	'admin_move' => '移動主題',
	'admin_highlight' => '高亮顯示',
	'admin_move_target' => '目標論壇',
	'admin_move_type' => '移動方式',
	'admin_move_redirect' => '移動主題並在原來的論壇中保留轉向',
	'admin_merge' => '合併主題',
	'admin_merge_tid' => '主題 tid',
	'admin_merge_tid_comment' => '即將與這個主題合併的 tid，如 viewthread.php?tid=48，tid 為 48',
	'admin_getip' => '查看 IP',
	'admin_getip_this' => '此用戶的 IP 地址是',
	'admin_ban_this_ip' => '禁止此 IP',
	'admin_highlight_style' => '字體樣式',
	'admin_highlight_color' => '字體顏色',
	'admin_highlight_bold' => '粗體',
	'admin_highlight_italic' => '斜體',
	'admin_highlight_underline' => '下劃線',
	'admin_digest_add' => '加入精華',
	'admin_digest_remove' => '解除精華',
	'admin_digest_addremove' => '加入/解除精華',
	'admin_delthreads' => '刪除選定主題',
	'admin_delposts' => '刪除選定文章',
	'admin_delthread' => '刪除主題',
	'admin_delpost' => '刪除文章',

	'whosonline' => '在線用戶',
	'online_only_guests' => '當前只有訪客或隱身會員在線',
	'online_action' => '當前動作',
	'online_in_forum' => '所在論壇',
	'online_in_thread' => '所在主題',
	'online_ip' => 'IP 地址',

	'post_percent' => '占全部文章的',
	'posts_per_day' => '平均每日發表文章',
	'personal_info' => '個人訊息',
	'somebodys_profile' => '$memberinfo[username] 的個人資料',
	'add_to_buddylist' => '加為好友',
	'search_posts' => '搜尋文章',
	'edit_member' => '編輯用戶',

	'poll_subject' => '投票標題',
	'poll_multiple' => '多選',
	'poll_single' => '單選',
	'poll_view_voters' => '[參與投票的會員]',
	'poll_voters' => '參與投票的會員',

	'last_thread' => '上一主題',
	'next_thread' => '下一主題',
	'disable_highlight' => '取消高亮',
	'unregistered' => '未註冊',
	'member_deleted' => '該用戶已被刪除',
	'regtime' => '註冊',
	'online_status' => '狀態',
	'attach_download_count' => '該附件被下載次數',
	'attach_img' => '本篇文章包含圖片附件',
	'attach_swf' => '本篇文章包含 Flash 附件',
	'click_open_newwindow' => '點擊查看全圖',

	'view_profile' => '查看資料',
	'send_mail' => '發送郵件',
	'visit_home' => '訪問主頁',
	'search_member_posts' => '搜尋該用戶的全部文章',
	'send_pm' => '發短訊息',
	'edit_post' => '編輯文章',
	'reply_quote' => '引用回覆',
	'report_to_moderator' => '向板主反應這個文章',
	'rate' => '評分',
	'thread_printable' => '可列印版本',
	'thread_email_friend' => '推薦給朋友',
	'thread_subscribe' => '訂閱主題',
	'thread_favorite' => '收藏主題',
	'thread_print' => '列印本頁',

	'pm_new' => '您有 $newpmnum 條新訊息',
	'pm_new_detail' => '[查看詳情]',
	'pm_new_ignore' => '[不再提示]',
	
	'pm_folders' => '文件夾',
	'pm_shortcut' => '快捷方式',
	'pm_send' => '發送短訊息',
	'pm_send_save_outbox' => '保存到發件箱中 &nbsp; [完成後可按 Ctrl+Enter 發布]',
	'pm_inbox' => '收件箱',
	'pm_outbox' => '發件箱',
	'pm_track' => '訊息跟蹤',
	'pm_data_usage' => '空間使用',
	'pm_total' => '共有短訊息',
	'pm_storage' => '短訊息上限',
	'pm_to_buddy' => '好友群發',
	'pm_buddy_checkall' => '全部好友',
	'pm_ignore' => '忽略列表',
	'pm_ignore_comment' => '增加多個忽略人員名單時用逗號 "," 隔開(如：張三,李四,王五等)。當這些被增加的忽略用戶給您發送短訊時將不予接收。',

	'faq_usermaint' => '用戶須知',

	'faq_usermaint_item1_q' => '我必須要註冊嗎？',
	'faq_usermaint_item2_q' => 'Discuz! 論壇使用 Cookies 嗎？',
	'faq_usermaint_item3_q' => '如何使用簽名？',
	'faq_usermaint_item4_q' => '如何使用個性化的頭像？',
	'faq_usermaint_item5_q' => '如果我遺忘了密碼，我該怎麼辦？',
	'faq_usermaint_item6_q' => '什麼是「短訊」？',

	'faq_usermaint_item1_a' => '&nbsp; &nbsp; 這取決於管理員如何設置 Discuz! 論壇的用戶組權限選項，您甚至有可能必須在註冊成正式用戶後後才能瀏覽文章。當然，在通常情況下，您至少應該是正式用戶才能發新文章和回覆已有文章。請 <a href="register.php">點擊這裡</a> 免費註冊成為我們的新用戶！<br><br>&nbsp; &nbsp; 強烈建議您註冊，這樣會得到很多以訪客身份無法實現的功能。',
	'faq_usermaint_item2_a' => '&nbsp; &nbsp; Discuz! 採用 Session+Cookie 的雙重方式保存用戶訊息，以確保在各種環境，包括 Cookie 完全無法使用的情況下您都能正常使用論壇各項功能。但 Cookies 的使用仍然可以為您帶來一系列的方便和好處，因此我們強烈建議您在正常情況下不要禁止 Cookie 的應用，Discuz! 的安全設計將全力保證您的資料安全。<br><br>&nbsp; &nbsp; 在登入頁面中，您可以選擇 Cookie 記錄時間，在該時間範圍內您打開瀏覽器訪問論壇將始終保持您上一次訪問時的登入狀態，而不必每次都輸入密碼。但基於安全考慮，如果您在公共電腦訪問論壇，建議選擇「瀏覽器進程」(預設)，或在離開公共計算機前選擇「退出」(<a href="logging.php?action=logout">點擊這裡</a> 退出論壇)以杜絕資料被非法使用的可能。',
	'faq_usermaint_item3_a' => '&nbsp; &nbsp; 簽名是加在您發表的文章下面的小段文字，註冊之後，您就可以設置自己的個性簽名了。<br><br>&nbsp; &nbsp; <a href="memcp.php">點擊這裡</a> 進入控制面板，在簽名框中輸入簽名文字，並確定不要超過管理員設置的相關限制(如字數、貼圖等)，這樣系統會自動選中您登入後發表文章頁面的顯示簽名選項，您的的簽名將在文章中自動被顯示。',
	'faq_usermaint_item4_a' => '&nbsp; &nbsp; 同樣在 <a href="memcp.php">控制面板</a> 中，有一處「頭像」選項。頭像是顯示在您用戶名下面的小圖像，使用頭像可能需要一定的權限，否則將不會顯示出來。詳情請查詢<a href="faq.php?page=misc#3">本論壇的級別設定</a>，一般頭像圖像寬度應控制在 150 像素以下，以免影響界面美觀。',
	'faq_usermaint_item5_a' => '&nbsp; &nbsp; Discuz! 提供發送取回密碼連結到 Email 的服務，點擊登入頁面中的 <a href="member.php?action=lostpasswd">取回密碼</a> 功能，可以為您把取回密碼的方法發送到註冊時填寫的 Email 信箱中。如果您的 Email 已失效或無法收到信件，請與論壇管理員聯繫。',
	'faq_usermaint_item6_a' => '&nbsp; &nbsp; 「短訊」是論壇註冊用戶間交流的工具，訊息只有發件和收件人可以看到，收到訊息後系統會出現鈴聲和相應提示，您可以通過短訊功能與同一論壇上的其他用戶保持私人聯繫。<a href="pm.php" target="_blank">收件箱</a> 或 <a href="memcp.php">控制面板</a> 中提供了短訊的收發服務。',

	'faq_using' => '論壇使用',
	'faq_using_item1_q' => '在哪裡可以登入？',
	'faq_using_item2_q' => '在哪裡可以退出？',
	'faq_using_item3_q' => '我要搜尋論壇，應該怎麼做？',
	'faq_using_item4_q' => '怎樣給其他人發送「短訊」？',
	'faq_using_item5_q' => '怎樣看到全部的會員？',

	'faq_using_item1_a' => '&nbsp; &nbsp; 如果您尚未登入，點擊左上角的「登入」，輸入用戶名和密碼，確定即可。如果需要保持登入，請選擇相應的 Cookie 時間，在此時間範圍內您可以不必輸入密碼而保持上次的登入狀態。',
	'faq_using_item2_a' => '&nbsp; &nbsp; 如果您已經登入，點擊左上角的「退出」，系統會清除 Cookie，退出登入狀態。',
	'faq_using_item3_a' => '&nbsp; &nbsp; 點擊上面的 <a href="search.php">搜尋</a>，輸入搜尋的關鍵字並選擇一個範圍，就可以檢索到您有權限訪問論壇中的相關的文章。',
	'faq_using_item4_a' => '&nbsp; &nbsp; 如果您已登入，菜單上會顯示出 <a href="pm.php" target="_blank">短訊</a>  項，點擊後彈出短訊窗口，通過類似發送郵件一樣的填寫，點「發送」，訊息就被發到對方收件箱中了。當他/她訪問論壇的主要頁面時，系統都會提示他/她收訊息。',
	'faq_using_item5_a' => '&nbsp; &nbsp; 當管理員設置可用此項功能時，您可以通過點擊 <a href="member.php?action=list">會員</a> 查看所有的會員及其資料，並可實現會員資料的檢索和排序輸出。',

	'faq_messages' => '讀寫文章和收發短訊',
	'faq_messages_item1_q' => '如何發布新文章？',
	'faq_messages_item2_q' => '如何回覆文章？',
	'faq_messages_item3_q' => '我能夠刪除主題嗎？',
	'faq_messages_item4_q' => '怎樣編輯自己發表的文章？',
	'faq_messages_item5_q' => '我可不可以上傳附件？',
	'faq_messages_item6_q' => '什麼是 Smilies？',
	'faq_messages_item7_q' => '該怎樣發起一個投票？',

	'faq_messages_item1_a' => '&nbsp; &nbsp; 在論壇板塊中，點「發新文章」即可進入功能齊全的發表文章界面。當然您也可以使用板塊下面的「快速發表文章」發表新文章(如果此選項打開)。注意，一般論壇都設置為需要登入後才能發表文章。',
	'faq_messages_item2_a' => '&nbsp; &nbsp; 在瀏覽文章時，點「回覆文章」即可進入功能齊全的回覆界面。當然您也可以使用板塊下面的「快速回覆」發表回覆(如果此選項打開)。注意，一般論壇都設置為需要登入後才能回覆。',
	'faq_messages_item3_a' => '&nbsp; &nbsp; 瀏覽文章時可以按下面的「編輯文章」，對於您自己發表的文章，可以很容易的編輯和刪除。但當這篇文章是整個主題的起始文章時，則會刪除該主題和全部回覆。',
	'faq_messages_item4_a' => '&nbsp; &nbsp; 和上面一樣，用「編輯文章」就可以編輯自己發表的文章。如果管理員通過論壇設置將這個功能遮蔽掉則不再可以進行此操作。',
	'faq_messages_item5_a' => '&nbsp; &nbsp; 可以。您可以在任何支援上傳附件的板塊中，通過發新文章、或者回覆的方式上傳附件（只要您的權限足夠）。附件不能超過系統限定尺寸，且在可用類型的範圍內才能上傳。',
	'faq_messages_item6_a' => '&nbsp; &nbsp; Smilies 是一些用字元表示的表情符號，如果打開 Smilies 功能，Discuz! 會把一些符號轉換成小圖像，顯示在文章中，更加美觀明瞭。目前支援下面這些 Smilies：<br>',
	'faq_messages_item7_a' => '&nbsp; &nbsp; 您可以像發表文章一樣在板塊中發起投票。每行輸入一個可能的選項（最多10個），您可以通過閱讀這個投票文章選出自己的答案，每人只能投票一次，之後將不能再對您的選擇做出更改。<br><br>&nbsp; &nbsp; 管理員擁有隨時關閉和修改投票選項的權力。',
	'faq_messages_smilies_code' => '表情符號',
	'faq_messages_smilies_image' => '對應圖像',


	'faq_misc' => '其他問題',
	'faq_misc_item1_q' => '能說明一下 Discuz! 代碼的用法嗎？',
	'faq_misc_item2_q' => '普通用戶如何成為板主？',
	'faq_misc_item3_q' => '我如何在 $bbname 具有更多的權限？',

	'faq_misc_item1_a' => '&nbsp; &nbsp; 您可以使用 Discuz! 代碼--一個 HTML 代碼的簡化版本，來簡化對文章顯示格式的控制。<br><br>
<ol type="1">
<li>[b]粗體文字 Abc[/b] &nbsp; 效果：<b>粗體文字 Abc</b> （粗體字）<br><br></li>
<li>[i]斜體文字 Abc[/i] &nbsp; 效果：<i>斜體文字 Abc</i> （斜體字）<br><br></li>
<li>[u]字下線文字 Abc[/u] &nbsp; 效果：<u>字下線文字 Abc</u> （字下線）<br><br></li>
<li>[fly]飛行文字 Abc[/fly] &nbsp; （飛行文字） &nbsp; 效果：<marquee width="90%" behavior="alternate" scrollamount="3">飛行文字 Abc</marquee><br><br></li>
<li>[color=red]紅顏色[/color] &nbsp; 效果：<font color="red">紅顏色</font> （改變文字顏色）<br><br></li>
<li>[size=3]文字大小為 3[/size] &nbsp; 效果：<font size="3">文字大小為 3</font> （改變文字大小）<br><br></li>
<li>[font=新細明體]字體為新細明體[/font] &nbsp; 效果：<font face"新細明體">字體為新細明體</font> （改變字體）<br><br></li>
<li>[align=Center]內容居中[/align] &nbsp; （格式內容位置） 效果：<br><center>內容居中</center><br></li>
<li>[url]http://www.crossday.com[/url] &nbsp; 效果：<a href="http://www.crossday.com" target="_blank">http://www.crossday.com</a> （超連結）<br><br></li>
<li>[url=http://www.Discuz.net]Discuz! 論壇[/url] &nbsp; 效果：<a href="http://www.Discuz.net" target="_blank">Discuz! 論壇</a> （超連結）<br><br></li>
<li>[email]support@crossday.com[/email] &nbsp; 效果：<a href="mailto:support@crossday.com">support@crossday.com</a> （E-Mail 連結）<br><br></li>
<li>[email=support@discuz.net]Discuz! 技術支援[/email] &nbsp; 效果：<a href="mailto:support@discuz.net">Discuz! 技術支援</a> （E-Mail 連結）<br><br></li>
<li>[quote]Discuz! Board 著作權所有 - Crossday Studio[/quote] &nbsp; （引用內容，類似的代碼還有 [code][/code]）<br><br></li>
<li>[hide]免費帳號為：163/163[/hide] &nbsp; （按回覆隱藏內容，僅限板主及管理員使用）<br>效果：只有當瀏覽者回覆本篇文章時，才顯示其中的內容，否則顯示為「<b>**** 隱藏訊息 回覆該系列文章後才能顯示 *****</b>」<br><br></li>
<li>[hide=20]免費帳號為：163/163[/hide] &nbsp; （按積分隱藏內容，僅限板主及管理員使用）<br>效果：只有當瀏覽者積分高於 20 點時，才顯示其中的內容，否則顯示為「<b>**** 隱藏訊息 積分高於 20 點才能顯示 ****</b>」<br><br></li>
<li>[list]<br>
[*]列表項 #1<br>
[*]列表項 #2<br>
[*]列表項 #2<br>
[/list] &nbsp; (列表)<br><br></li>
<br>以下 Discuz! 代碼需論壇可用 [img] 代碼才能使用<hr noshade size="0" width="50%" color="{BORDERCOLOR}" align="left"><br>
<li>[iframe]http://www.crossday.com[/iframe] &nbsp; （在文章中鑲嵌網頁）<br><br></li>
<li>[img]http://www.crossday.com/statdard/images/logo.gif[/img] &nbsp; （連結圖像）<br>效果：<br><img src="images/standard/logo.gif"> <br><br></li>
<li>[img=88,31]http://www.crossday.com/images/logo.gif[/img] &nbsp;（連結圖像並限制大小）<br> 效果：<br><img src="images/logo.gif" height="31" width="88"> <br><br></li>
<li>[swf]http://www.crossday.com/discuz/images/banner.swf[/swf] &nbsp; （連結 flash 動畫，用法與 [img] 類似）<br><br></li>
<li>[swf=88,31]http://www.crossday.com/discuz/images/banner.swf[/swf] &nbsp;（連結 flash 動畫並限制大小，用法與 [img] 類似）<br><br></li>
<li>[wmv][/wmv]、[mid][/mid]、[ra][/ra]、[rm][/rm] &nbsp; （用於在文章中插入上述多媒體格式文件，用法與其他 Discuz! 代碼類似）<br><br></li>
</ol>',
	'faq_misc_item2_a' => '&nbsp; &nbsp; 論壇的板主是自願申請的，管理員可能會要求板主需要達到一定積分，或在論壇註冊超過一定時間等。板主應該是誠實守信、樂於助人、大公無私的表率，同時還要熟悉專業，經驗豐富，有良好的口碑。如果您確認已經達到上面幾點，並希望擔任本站的板主，可以與管理員聯繫。',
	'faq_misc_item3_a' => '&nbsp; &nbsp; 本站所使用的 Discuz! 論壇是按照系統頭銜和用戶積分區分的，積分可以參考您的發表文章量，其他用戶的評分，或兩者綜合來決定。
當積分達到一定等級要求時，系統會自動為您開通新的權限，並給予相應星星標誌。因此，擁有較高的積分數，不僅代表您在本論壇的資歷與活躍程度，同時也意味著能夠擁有比其他用戶更多的高級權限。'
);

?>